baseURL = "https://bgdistributed.org/"
title = "BG Distributed"

theme = "blowfish"

enableRobotsTXT = true

defaultContentLanguage = "en"

homepage.layout = "profile"

[languages]
  [languages.en]
    label = "en"

[pagination]
pagerSize = 10


